### ISSUE TITLE
为什么不把Files页面的链接翻译成“文件”呢

### ISSUE THREAD

**Issue by reserveword** [Yesterday17/curseforge-chinese-fix#1]
![default](https://user-images.githubusercontent.com/12995615/51452094-8917e580-1d73-11e9-967a-12dcdfc59530.png)

“发布版本”这样的翻译挺奇怪的，像是我要去发布东西一样。
直译成”文件“不好吗？
即使要意译，译成“版本”、”版本选择“、”下载“都更通顺吧

**Comment by Yesterday17** [comment]
这里当初想对应的是`Recent Files`里的`Files`，个人认为`最近发布的版本`比`最近文件`更通顺。
但这里确实有点不大直观了，我改一下吧。
